version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=102030
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

